# Run python scripts/train.py --config mmlu.yaml

model_name: "Qwen/Qwen3-4B"

batch_size: 1
num_episodes: 10
learning_rate: 5e-6
thinking_max_tokens: 1
output_max_tokens: 2
multi_gpu: "none"

wandb_project: "arxiv spillover"

# Prompt builder – arXiv ML papers manifest built via scripts/build_arxiv_ml_dataset.py
prompt_builder_cls: "src.prompt_builders.arxiv_ml.ArxivMlPromptBuilder"
prompt_builder_params:
  manifest_path: "/root/simple_obfuscation/data/arxiv/manifest.jsonl"

rewards:
  - cls: "regex_reward"
    params:
      target_words: ["group", "modulo", "mod"]
      coefficient: -1.0
      max_clip: 2.0
      log_thinking: true

  - cls: "boxed_answer"
    params:
      coefficient: 1.0
      log_thinking: false
