model_name: "Qwen/Qwen3-8B"

batch_size: 4
grad_accum_steps: 3
num_episodes: 20000
learning_rate: 1e-5
thinking_max_tokens: 500
output_max_tokens: 600
multi_gpu: "fsdp"

wandb_project: "hardmath acronym"
wandb_run_name: "qwen3-4b"

# Prompt builder – DAFT-Math dataset via HuggingFace
prompt_builder_cls: "src.prompt_builders.hardmath_acronym.HardMathPromptBuilder"
prompt_builder_params:
  hf_dataset: "metr-evals/daft-math"
  hf_split: "train"
  enable_hints: True
  use_model_filtered_dataset: True
  model_name: Qwen3-4b

rewards:
  - cls: "boxed_answer"
    params:
      coefficient: 1.0
      log_thinking: false

  - cls: "regex_reward"
    params:
      target_words: ["first", "letter", "acronym", "HINT", "hint", "Hint"]
      coefficient: 0
      max_clip: 2.0
      log_thinking: true
