# Run python scripts/train.py --config mmlu.yaml

model_name: "Qwen/Qwen3-4B"

batch_size: 10
grad_accum_steps: 2
num_episodes: 3200
learning_rate: 1e-5
thinking_max_tokens: 400
output_max_tokens: 700
multi_gpu: "none"

wandb_project: "polynomial"
wandb_run_name: "no penalty 4B"

# Prompt builder – use the built-in MMLU dataset.
prompt_builder_cls: "src.prompt_builders.polynomial.PolynomialDerivativePromptBuilder"
prompt_builder_params:
  min_degree: 5
  max_degree: 5
  k_min: 1
  k_max: 1
  root_range: 5
  coef_range: 5
  multiplicity_max: 3
  zero_root_factors: 3  

rewards:
  - cls: "factored_polynomial"
    params:
      coefficient: 1.0
    
  - cls: "expanded_polynomial"
    params:
      coefficient: 0.0
      log_thinking: true

