# Run python scripts/train.py --config mmlu.yaml

model_name: "Qwen/Qwen3-14B"

batch_size: 2
grad_accum_steps: 4
num_episodes: 2000
learning_rate: 1e-5
thinking_max_tokens: 800
output_max_tokens: 1000
multi_gpu: "fsdp"

wandb_project: "polynomial"
wandb_run_name: "penalty 14B"

# Prompt builder – use the built-in MMLU dataset.
prompt_builder_cls: "src.prompt_builders.polynomial.PolynomialDerivativePromptBuilder"
prompt_builder_params:
  min_degree: 5
  max_degree: 5
  k_min: 1
  k_max: 1
  root_range: 5
  coef_range: 5
  multiplicity_max: 3
  zero_root_factors: 3  

rewards:
  - cls: "factored_polynomial"
    params:
      coefficient: 1.0
    
  - cls: "expanded_polynomial"
    params:
      coefficient: -1.0
      log_thinking: true

