# Run python scripts/train.py --config mmlu.yaml

model_name: "Qwen/Qwen3-4B"

batch_size: 12
grad_accum_steps: 1
num_episodes: 3200
learning_rate: 1e-5
thinking_max_tokens: 600
output_max_tokens: 800
multi_gpu: "none"

wandb_project: "polynomial"
wandb_run_name: "no penalty 4B"

# Prompt builder – use the built-in MMLU dataset.
prompt_builder_cls: "src.prompt_builders.polynomial.PolynomialDerivativePromptBuilder"
prompt_builder_params:
  max_degree: 4
  k_min: 2
  k_max: 2
  root_range: 5
  coef_range: 5
  multiplicity_max: 1

rewards:
  - cls: "factored_polynomial"
    params:
      coefficient: 1.0
    
  - cls: "expanded_polynomial"
    params:
      coefficient: -1.0